# Generated by Django 4.2.30 on 2026-06-14 13:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='宝宝昵称')),
                ('gender', models.CharField(choices=[('M', '男宝'), ('F', '女宝'), ('U', '未知')], default='U', max_length=1, verbose_name='性别')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '宝宝档案',
                'verbose_name_plural': '宝宝档案',
                'db_table': 'baby',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='物品名称')),
                ('category', models.CharField(choices=[('onesie', '连体衣'), ('tshirt', 'T恤'), ('shirt', '衬衫'), ('pants', '裤子'), ('shorts', '短裤'), ('dress', '连衣裙'), ('skirt', '裙子'), ('coat', '外套'), ('jacket', '夹克'), ('sweater', '毛衣'), ('hoodie', '卫衣'), ('underwear', '内衣'), ('socks', '袜子'), ('shoes', '鞋子'), ('hat', '帽子'), ('bib', '围兜'), ('blanket', '毯子'), ('sleepwear', '睡衣'), ('swimwear', '泳装'), ('other', '其他')], max_length=30, verbose_name='品类')),
                ('size_type', models.CharField(choices=[('height', '按身高码'), ('age', '按月龄码'), ('eu', '欧码'), ('us', '美码'), ('cn', '国标码')], default='height', max_length=10, verbose_name='尺码类型')),
                ('size_value', models.CharField(max_length=20, verbose_name='尺码值')),
                ('size_label', models.CharField(blank=True, max_length=50, verbose_name='尺码标签展示')),
                ('min_height', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='适合最小身高(cm)')),
                ('max_height', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='适合最大身高(cm)')),
                ('min_age_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='适合最小月龄')),
                ('max_age_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='适合最大月龄')),
                ('season', models.CharField(choices=[('spring', '春季'), ('summer', '夏季'), ('autumn', '秋季'), ('winter', '冬季'), ('all', '四季通用')], max_length=10, verbose_name='适用季节')),
                ('condition', models.CharField(choices=[('new', '全新'), ('like_new', '9成新'), ('good', '8成新'), ('fair', '7成新'), ('worn', '有使用痕迹')], default='good', max_length=10, verbose_name='成色')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购入时间')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='购入价格')),
                ('status', models.CharField(choices=[('keep', '自留'), ('to_give', '待转送'), ('reserved', '已预定'), ('given', '已送出')], default='keep', max_length=10, verbose_name='当前状态')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='图片链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='closet.baby', verbose_name='所属宝宝')),
            ],
            options={
                'verbose_name': '衣物档案',
                'verbose_name_plural': '衣物档案',
                'db_table': 'clothing_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='接收人姓名')),
                ('relation', models.CharField(blank=True, max_length=50, verbose_name='与您关系')),
                ('baby_name', models.CharField(blank=True, max_length=50, verbose_name='对方宝宝姓名')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='联系方式')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '转送对象',
                'verbose_name_plural': '转送对象',
                'db_table': 'transfer_recipient',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='接收人(冗余)')),
                ('transfer_date', models.DateField(verbose_name='交接时间')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '待交接'), ('completed', '已完成'), ('cancelled', '已取消')], default='completed', max_length=10, verbose_name='转送状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='closet.clothingitem', verbose_name='物品')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='closet.transferrecipient', verbose_name='转送对象')),
            ],
            options={
                'verbose_name': '转送记录',
                'verbose_name_plural': '转送记录',
                'db_table': 'transfer_record',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='身高(cm)')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='体重(kg)')),
                ('head_circumference', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='头围(cm)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='closet.baby', verbose_name='宝宝')),
            ],
            options={
                'verbose_name': '成长记录',
                'verbose_name_plural': '成长记录',
                'db_table': 'growth_record',
                'ordering': ['-record_date'],
            },
        ),
    ]
