# Generated by Django 4.2.30 on 2026-06-14 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('target_season', models.CharField(choices=[('spring', '春季'), ('summer', '夏季'), ('autumn', '秋季'), ('winter', '冬季')], max_length=10, verbose_name='目标季节')),
                ('plan_date', models.DateField(verbose_name='计划日期')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='完成时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_progress', '进行中'), ('completed', '已完成')], default='draft', max_length=15, verbose_name='计划状态')),
                ('note', models.TextField(blank=True, null=True, verbose_name='整理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_plans', to='closet.baby', verbose_name='宝宝')),
            ],
            options={
                'verbose_name': '换季整理计划',
                'verbose_name_plural': '换季整理计划',
                'db_table': 'season_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeasonPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_category', models.CharField(choices=[('continue_wear', '本季可继续穿'), ('near_unsuitable', '即将不合身'), ('suggest_transfer', '建议转送'), ('next_season_prep', '下一季待准备')], max_length=20, verbose_name='系统自动分类')),
                ('user_category', models.CharField(blank=True, choices=[('continue_wear', '本季可继续穿'), ('near_unsuitable', '即将不合身'), ('suggest_transfer', '建议转送'), ('next_season_prep', '下一季待准备')], max_length=20, null=True, verbose_name='用户调整分类')),
                ('item_status_action', models.CharField(choices=[('to_give', '标记待转送'), ('reserved', '标记已预定'), ('keep', '继续自留'), ('none', '无操作')], default='none', max_length=15, verbose_name='批量操作状态')),
                ('item_name', models.CharField(blank=True, max_length=200, verbose_name='物品名称(冗余)')),
                ('item_category', models.CharField(blank=True, max_length=30, verbose_name='品类(冗余)')),
                ('item_size_label', models.CharField(blank=True, max_length=50, verbose_name='尺码(冗余)')),
                ('item_season', models.CharField(blank=True, max_length=10, verbose_name='季节(冗余)')),
                ('item_condition', models.CharField(blank=True, max_length=10, verbose_name='成色(冗余)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_plan_items', to='closet.clothingitem', verbose_name='衣物')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='closet.seasonplan', verbose_name='所属计划')),
            ],
            options={
                'verbose_name': '换季计划条目',
                'verbose_name_plural': '换季计划条目',
                'db_table': 'season_plan_item',
                'ordering': ['auto_category', '-created_at'],
            },
        ),
    ]
