# Generated by Django 4.2.30 on 2026-06-15 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_seasonplan_seasonplanitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='借穿人姓名')),
                ('relation', models.CharField(blank=True, choices=[('family', '家人'), ('relative', '亲戚'), ('friend', '朋友'), ('neighbor', '邻居'), ('colleague', '同事'), ('other', '其他')], max_length=20, verbose_name='与您关系')),
                ('baby_name', models.CharField(blank=True, max_length=50, verbose_name='对方宝宝姓名')),
                ('baby_gender', models.CharField(choices=[('M', '男宝'), ('F', '女宝'), ('U', '未知')], default='U', max_length=1, verbose_name='宝宝性别')),
                ('baby_birth_date', models.DateField(blank=True, null=True, verbose_name='宝宝出生日期')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='联系方式')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '借穿对象',
                'verbose_name_plural': '借穿对象',
                'db_table': 'borrow_object',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='status',
            field=models.CharField(choices=[('keep', '自留'), ('to_give', '待转送'), ('reserved', '已预定'), ('given', '已送出'), ('lent', '借出中')], default='keep', max_length=10, verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='seasonplanitem',
            name='auto_category',
            field=models.CharField(choices=[('continue_wear', '本季可继续穿'), ('near_unsuitable', '即将不合身'), ('suggest_transfer', '建议转送'), ('next_season_prep', '下一季待准备'), ('lent', '暂不可整理(借出中)')], max_length=20, verbose_name='系统自动分类'),
        ),
        migrations.AlterField(
            model_name='seasonplanitem',
            name='user_category',
            field=models.CharField(blank=True, choices=[('continue_wear', '本季可继续穿'), ('near_unsuitable', '即将不合身'), ('suggest_transfer', '建议转送'), ('next_season_prep', '下一季待准备'), ('lent', '暂不可整理(借出中)')], max_length=20, null=True, verbose_name='用户调整分类'),
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(blank=True, max_length=100, verbose_name='借穿人(冗余)')),
                ('baby_name', models.CharField(blank=True, max_length=50, verbose_name='借穿宝宝(冗余)')),
                ('borrow_date', models.DateField(verbose_name='借出时间')),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='预计归还时间')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='实际归还时间')),
                ('status', models.CharField(choices=[('borrowed', '借出中'), ('overdue', '逾期未还'), ('returned', '已归还'), ('returned_damaged', '归还有损坏')], default='borrowed', max_length=20, verbose_name='归还状态')),
                ('original_condition', models.CharField(choices=[('new', '全新'), ('like_new', '9成新'), ('good', '8成新'), ('fair', '7成新'), ('worn', '有使用痕迹')], max_length=10, verbose_name='借出时成色')),
                ('return_condition', models.CharField(blank=True, choices=[('new', '全新'), ('like_new', '9成新'), ('good', '8成新'), ('fair', '7成新'), ('worn', '有使用痕迹')], max_length=10, null=True, verbose_name='归还时成色')),
                ('condition_change', models.CharField(blank=True, choices=[('same', '无变化'), ('slight', '轻微变旧'), ('noticeable', '明显变旧'), ('damaged', '有损坏')], max_length=20, null=True, verbose_name='成色变化')),
                ('wash_status', models.CharField(choices=[('unwashed', '未清洗'), ('washed', '已清洗'), ('to_wash', '需清洗后归还')], default='unwashed', max_length=20, verbose_name='清洗状态')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('return_note', models.TextField(blank=True, null=True, verbose_name='归还备注')),
                ('suggest_transfer', models.BooleanField(default=False, verbose_name='建议转送')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_records', to='closet.borrowobject', verbose_name='借穿对象')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='closet.clothingitem', verbose_name='借出物品')),
            ],
            options={
                'verbose_name': '借穿记录',
                'verbose_name_plural': '借穿记录',
                'db_table': 'borrow_record',
                'ordering': ['-borrow_date', '-created_at'],
            },
        ),
    ]
