# Generated by Django 4.2.30 on 2026-06-15 02:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_borrowobject_alter_clothingitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='care_note',
            field=models.TextField(blank=True, null=True, verbose_name='护理备注'),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='care_status',
            field=models.CharField(choices=[('to_wash', '待清洗'), ('washing', '清洗中'), ('to_dry', '待晾晒'), ('drying', '晾晒中'), ('to_sterilize', '需消毒'), ('sterilizing', '消毒中'), ('to_store', '待入柜'), ('stored', '已入柜'), ('in_use', '穿着中')], default='stored', max_length=15, verbose_name='护理状态'),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='last_store_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后入柜时间'),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='last_wash_date',
            field=models.DateField(blank=True, null=True, verbose_name='最后清洗时间'),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='preferred_dry_method',
            field=models.CharField(blank=True, choices=[('natural_shade', '阴干'), ('natural_sun', '日晒'), ('dryer_low', '烘干机低温'), ('dryer_normal', '烘干机常温'), ('flat_dry', '平铺晾晒')], default='natural_shade', max_length=20, verbose_name='推荐晾晒方式'),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='preferred_sterilize_method',
            field=models.CharField(blank=True, choices=[('none', '无需消毒'), ('sunlight', '阳光暴晒'), ('steam', '蒸汽消毒'), ('uv', '紫外线消毒'), ('boil', '煮沸消毒'), ('disinfectant', '消毒液浸泡')], default='sunlight', max_length=20, verbose_name='推荐消毒方式'),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='preferred_wash_method',
            field=models.CharField(blank=True, choices=[('hand', '手洗'), ('machine_normal', '机洗普通'), ('machine_gentle', '机洗轻柔'), ('dry_clean', '干洗'), ('wipe', '擦拭清洁')], default='machine_gentle', max_length=20, verbose_name='推荐清洗方式'),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='wash_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='累计清洗次数'),
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='位置名称')),
                ('location_type', models.CharField(choices=[('wardrobe', '衣柜'), ('drawer', '抽屉'), ('shelf', '架子'), ('box', '收纳箱'), ('hanger', '挂架'), ('basket', '收纳篮'), ('bag', '收纳袋'), ('other', '其他')], default='wardrobe', max_length=20, verbose_name='位置类型')),
                ('container_name', models.CharField(blank=True, max_length=100, verbose_name='收纳容器/编号')),
                ('area', models.CharField(blank=True, help_text='例如：主卧、儿童房、储物间', max_length=100, verbose_name='所在区域')),
                ('shelf_level', models.CharField(blank=True, help_text='例如：上层、中层、第三格', max_length=50, verbose_name='层/格位置')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='closet.baby', verbose_name='所属宝宝')),
            ],
            options={
                'verbose_name': '收纳位置',
                'verbose_name_plural': '收纳位置',
                'db_table': 'storage_location',
                'ordering': ['sort_order', 'name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('wash', '清洗'), ('dry', '晾晒'), ('sterilize', '消毒'), ('store', '入柜'), ('retrieve', '取出使用'), ('other', '其他护理')], max_length=15, verbose_name='护理类型')),
                ('care_date', models.DateField(default=datetime.date.today, verbose_name='护理日期')),
                ('care_time', models.DateTimeField(auto_now_add=True, verbose_name='护理时间')),
                ('wash_method', models.CharField(blank=True, choices=[('hand', '手洗'), ('machine_normal', '机洗普通'), ('machine_gentle', '机洗轻柔'), ('dry_clean', '干洗'), ('wipe', '擦拭清洁')], max_length=20, null=True, verbose_name='清洗方式')),
                ('dry_method', models.CharField(blank=True, choices=[('natural_shade', '阴干'), ('natural_sun', '日晒'), ('dryer_low', '烘干机低温'), ('dryer_normal', '烘干机常温'), ('flat_dry', '平铺晾晒')], max_length=20, null=True, verbose_name='晾晒方式')),
                ('sterilize_method', models.CharField(blank=True, choices=[('none', '无需消毒'), ('sunlight', '阳光暴晒'), ('steam', '蒸汽消毒'), ('uv', '紫外线消毒'), ('boil', '煮沸消毒'), ('disinfectant', '消毒液浸泡')], max_length=20, null=True, verbose_name='消毒方式')),
                ('detergent_used', models.CharField(blank=True, max_length=100, verbose_name='使用洗涤剂')),
                ('water_temperature', models.CharField(blank=True, help_text='例如：30度以下、冷水、温水', max_length=20, verbose_name='水温')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='处理时长(分钟)')),
                ('care_note', models.TextField(blank=True, null=True, verbose_name='护理备注')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_records', to='closet.clothingitem', verbose_name='衣物')),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_records', to='closet.storagelocation', verbose_name='入柜位置')),
            ],
            options={
                'verbose_name': '护理记录',
                'verbose_name_plural': '护理记录',
                'db_table': 'care_record',
                'ordering': ['-care_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothes', to='closet.storagelocation', verbose_name='收纳位置'),
        ),
    ]
