# Generated by Django 4.2.30 on 2026-06-15 03:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0004_clothingitem_care_note_clothingitem_care_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='套装名称')),
                ('scene', models.CharField(choices=[('daily_outing', '日常外出'), ('kindergarten', '幼儿园备用'), ('travel', '旅行过夜'), ('photo', '拍照穿搭'), ('emergency_cold', '降温应急包'), ('other', '其他')], max_length=20, verbose_name='适用场景')),
                ('season', models.CharField(choices=[('spring', '春季'), ('summer', '夏季'), ('autumn', '秋季'), ('winter', '冬季'), ('all', '四季通用')], default='all', max_length=10, verbose_name='适用季节')),
                ('min_temperature', models.IntegerField(blank=True, null=True, verbose_name='适用最低温度(℃)')),
                ('max_temperature', models.IntegerField(blank=True, null=True, verbose_name='适用最高温度(℃)')),
                ('backup_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='备用数量')),
                ('use_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='使用次数')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最近使用时间')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_sets', to='closet.baby', verbose_name='所属宝宝')),
            ],
            options={
                'verbose_name': '衣物套装',
                'verbose_name_plural': '衣物套装',
                'db_table': 'outfit_set',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutfitSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('must', '必带'), ('optional', '可选')], default='must', max_length=10, verbose_name='物品类型')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_items', to='closet.clothingitem', verbose_name='衣物')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_items', to='closet.outfitset', verbose_name='所属套装')),
            ],
            options={
                'verbose_name': '套装明细',
                'verbose_name_plural': '套装明细',
                'db_table': 'outfit_set_item',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('scene', models.CharField(blank=True, choices=[('daily_outing', '日常外出'), ('kindergarten', '幼儿园备用'), ('travel', '旅行过夜'), ('photo', '拍照穿搭'), ('emergency_cold', '降温应急包'), ('other', '其他')], max_length=20, null=True, verbose_name='出行场景')),
                ('trip_date', models.DateField(blank=True, null=True, verbose_name='出行日期')),
                ('packing_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='打包完成时间')),
                ('status', models.CharField(choices=[('draft', '待打包'), ('packing', '打包中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=15, verbose_name='任务状态')),
                ('missing_count', models.IntegerField(default=0, verbose_name='缺失物品数')),
                ('replace_count', models.IntegerField(default=0, verbose_name='替换物品数')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_tasks', to='closet.baby', verbose_name='所属宝宝')),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_tasks', to='closet.outfitset', verbose_name='关联套装')),
            ],
            options={
                'verbose_name': '打包任务',
                'verbose_name_plural': '打包任务',
                'db_table': 'packing_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackingCheckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='物品名称')),
                ('item_category', models.CharField(blank=True, max_length=30, verbose_name='物品品类')),
                ('item_type', models.CharField(choices=[('must', '必带'), ('optional', '可选')], default='must', max_length=10, verbose_name='物品类型')),
                ('pack_status', models.CharField(choices=[('pending', '待确认'), ('packed', '已打包'), ('replaced', '已替换'), ('missing', '缺失')], default='pending', max_length=10, verbose_name='打包状态')),
                ('original_available', models.BooleanField(default=True, verbose_name='原物是否可用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('original_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='closet.clothingitem', verbose_name='原衣物')),
                ('replaced_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='closet.clothingitem', verbose_name='替换衣物')),
                ('set_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_records', to='closet.outfitsetitem', verbose_name='套装明细')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_items', to='closet.packingtask', verbose_name='所属打包任务')),
            ],
            options={
                'verbose_name': '打包检查记录',
                'verbose_name_plural': '打包检查记录',
                'db_table': 'packing_check_record',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
